### ISSUE TITLE
Help getting up and running?

### ISSUE THREAD

**Issue by jcderr** [dwimberger/crowd-radius-server#1]
We don't seem to be able to get this up and running, and suspect we're missing a pre-req or perhaps a mvn job that needs to be run? Perhaps you can help us.

$ mvn package
[ ... ]
$ ./run.sh
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Crowd-Radius-Server 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) @ crowd-radius-server >>>
[INFO] 
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) @ crowd-radius-server <<<
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ crowd-radius-server ---
[WARNING] 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.NoClassDefFoundError: org/tinyradius/attribute/RadiusAttribute
    at net.wimpi.crowd.radius.Server.main(Server.java:21)
    ... 6 more
Caused by: java.lang.ClassNotFoundException: org.tinyradius.attribute.RadiusAttribute
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 7 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.816s
[INFO] Finished at: Thu Jul 11 13:27:35 CDT 2013
[INFO] Final Memory: 6M/81M

**Comment by dwimberger** [comment]
Hi Jeremy,

Could you post the output of your mvn package?
Also the output of 
    jar -tvf target/crowd-radius-server-1.0-SNAPSHOT.jar
could be helpful to diagnose if the packaging worked ok.

It does not seem to run correctly, otherwise the shade plugin should package the library from lib.

You can also try to directly run 
    java -cp target/crowd-radius-server-1.0-SNAPSHOT.jar net.wimpi.crowd.radius.Server config.properties

Regards,
Dieter

**Comment by jcderr** [comment]
I managed to weasel it out by mvn installing tinyradius.jar into my local repo and tweaking the pom to depend on it.

**Comment by dwimberger** [comment]
Probably it was something with the local paths.
I'll close this issue. If the dependency pops up in a repository, I'll replace the library.

**Comment by Antairez** [comment]
I'm sorry I'm getting the exact same problems. Is there a solution?
