### ISSUE TITLE
Failed to build Crowd-Radius-Server 1.0-SNAPSHOT

### ISSUE THREAD

**Issue by Antairez** [dwimberger/crowd-radius-server#5]
Hi, noob here, sorry. Tried to run run.sh but the package won't build. Followed the configuration in Wiki and everything I could find on this project. Please help, thank you! (Built using java 1.8)

```
ubuntu@localhost:/opt/crowd-radius-server-master$ ./run.sh
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Crowd-Radius-Server 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ crowd-radius-server ---
[WARNING]
java.lang.ClassNotFoundException: net.wimpi.crowd.radius.Server
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:281)
        at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.233s
[INFO] Finished at: Tue Sep 06 05:18:38 UTC 2016
[INFO] Final Memory: 9M/22M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:java (default-cli) on project crowd-radius-server: An exception occured while executing the Java class. net.wimpi.crowd.radius.Server -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by Antairez** [comment]
Sorry didn't know I need to run mvn package first
